/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#e2c19c',
        'inverse-on-surface': '#f2f0f2',
        'error-container': '#ffdad6',
        error: '#ba1a1a',
        'on-primary-fixed-variant': '#3b475b',
        'on-tertiary-fixed-variant': '#594326',
        'inverse-surface': '#303032',
        'primary-fixed': '#d6e3fc',
        'tertiary-fixed': '#ffddb7',
        'surface-tint': '#525f74',
        'on-surface': '#1b1b1d',
        background: '#fbf9fa',
        'on-tertiary-fixed': '#291802',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        surface: '#fbf9fa',
        'secondary-container': '#d5e3fd',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed': '#0d1c2f',
        'inverse-primary': '#bac7df',
        'on-primary-fixed': '#0f1c2e',
        'primary-fixed-dim': '#bac7df',
        'secondary-fixed-dim': '#b9c7e0',
        'surface-container-highest': '#e4e2e3',
        'surface-container-high': '#eae7e9',
        'primary-container': '#0f1c2e',
        'surface-container': '#f0edef',
        'on-error-container': '#93000a',
        primary: '#000000',
        outline: '#75777d',
        'outline-variant': '#c5c6cd',
        secondary: '#515f74',
        tertiary: '#000000',
        'on-secondary-fixed-variant': '#3a485c',
        'surface-bright': '#fbf9fa',
        'tertiary-container': '#291802',
        'on-primary': '#ffffff',
        'surface-container-low': '#f5f3f5',
        'on-secondary-container': '#57657b',
        'on-background': '#1b1b1d',
        'secondary-fixed': '#d5e3fd',
        'on-surface-variant': '#44474c',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#9b7f5e',
        'surface-variant': '#e4e2e3',
        'surface-dim': '#dbd9db',
        'on-primary-container': '#78849b',
        brand: {
          navy: '#0F1C2E',
          amber: '#F59E0B',
        },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        'margin-mobile': '16px',
        gutter: '24px',
        'container-max': '1440px',
        'margin-tablet': '32px',
        base: '8px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        sans: ['Geist', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-lg': ['Geist'],
        'headline-lg-mobile': ['Geist'],
        'body-md': ['Geist'],
        'title-md': ['Geist'],
        'body-lg': ['Geist'],
        'display-lg': ['Geist'],
        'display-xl': ['Geist'],
        'label-sm': ['Geist'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'display-xl': ['72px', { lineHeight: '80px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
